# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RC_C <- function(coeflistS, U_pre, alpha, z) {
    .Call(`_QIoT_RC_C`, coeflistS, U_pre, alpha, z)
}

RS_C <- function(lst, C, Aplus, Aminus, values) {
    .Call(`_QIoT_RS_C`, lst, C, Aplus, Aminus, values)
}

add_C <- function(L, R, p) {
    .Call(`_QIoT_add_C`, L, R, p)
}

LpGreedy_On_C <- function(coeflist, p) {
    .Call(`_QIoT_LpGreedy_On_C`, coeflist, p)
}

DP_C <- function(coeflist, p) {
    .Call(`_QIoT_DP_C`, coeflist, p)
}

rank_score <- function(n, method_list) {
    .Call(`_QIoT_rank_score`, n, method_list)
}

fir_rank <- function(x) {
    .Call(`_QIoT_fir_rank`, x)
}

min_stat <- function(Z, Y, k, c, method_list, score = NULL) {
    .Call(`_QIoT_min_stat`, Z, Y, k, c, method_list, score)
}

combnCpp <- function(n, k) {
    .Call(`_QIoT_combnCpp`, n, k)
}

null_dist <- function(n, m, method_list_ = NULL, score_ = NULL, Z_perm_ = NULL, null_max = 1e5) {
    .Call(`_QIoT_null_dist`, n, m, method_list_, score_, Z_perm_, null_max)
}

test_stat_matrix_block <- function(Z, Y, block, c, method_list_all) {
    .Call(`_QIoT_test_stat_matrix_block`, Z, Y, block, c, method_list_all)
}

null_dist_block_C <- function(Z, block, method_list_all, null_max = 1e5, Z_perm_ = NULL) {
    .Call(`_QIoT_null_dist_block_C`, Z, block, method_list_all, null_max, Z_perm_)
}

